FROM node:20.15.1

# Create home directory
ENV APP_ROOT /opt/app
RUN mkdir $APP_ROOT
WORKDIR $APP_ROOT

# Activate corepack
RUN corepack enable npm
RUN corepack enable yarn
RUN corepack enable pnpm

# Install pnpm
ENV PNPM_VERSION=9.5.0
RUN corepack use pnpm@$PNPM_VERSION

# Avoid ERR_PNPM_ENOENT error
RUN pnpm config set store-dir /tmp/pnpm/store
