FROM node:20.15.1

# Create home directory
ENV APP_ROOT /opt/app
RUN mkdir $APP_ROOT
WORKDIR $APP_ROOT

# Install pnpm
RUN wget -qO- https://get.pnpm.io/install.sh | ENV="$HOME/.bashrc" SHELL="$(which bash)" bash -

# Allow only pnpm to be used
RUN corepack enable npm
RUN corepack enable yarn
