FROM node:20.15.1

# Create home directory
ENV APP_ROOT /opt/app
RUN mkdir $APP_ROOT
WORKDIR $APP_ROOT

# Activate corepack
RUN corepack enable npm
RUN corepack enable yarn
RUN corepack enable pnpm

# Install pnpm
ENV PNPM_VERSION=9.5.0
RUN corepack use pnpm@$PNPM_VERSION

# Install tbls
ENV TBLS_VERSION=1.76.1
RUN curl -o tbls.deb -L https://github.com/k1LoW/tbls/releases/download/v$TBLS_VERSION/tbls_$TBLS_VERSION-1_arm64.deb
RUN dpkg -i tbls.deb
